### ISSUE TITLE
Bad alignment in metrics

### ISSUE THREAD

**Issue by Gabriel-p** [adsabs/bumblebee#1010]
The 'Ref' list need to be more separated from 'Stacked'.

![captura de pantalla de 2016-07-14 13 09 04](https://cloud.githubusercontent.com/assets/6054951/16846792/30088d4e-49c4-11e6-83c8-06aa15383041.png)

**Comment by aholachek** [comment]
hi @Gabriel-p, thanks for pointing this out. It's now (finally) been fixed and the update should be in bumblebee in the next few days.
