### ISSUE TITLE
carolyn mentioned a bug involving occasionally missing dois

### ISSUE THREAD

**Issue by aholachek** [adsabs/bumblebee#1025]

**Comment by csgrant00** [comment]
Searching for bibstem:"pyas" year:2016 returns a list with no publisher links (even though they all
have DOIs) and if you click on an individual abstract, you can't see the DOI until you reload the page (at least in firefox).

**Comment by aaccomazzi** [comment]
Related to this: for some reason the record 2016pyas.confE....J has a link to "publisher article" while the record 2016pyas.confE..35R does not.  Both SOLR documents seem to have the same "links_data" structure in our local instance, so...?

**Comment by aaccomazzi** [comment]
Somehow the record in AWS's SOLR for `2016pyas.confE..35R` does not match what is in our local SOLR instance:

AWS:
```
        "bibcode": "2016pyas.confE..35R",
        "indexstamp": "2016-07-13T01:50:49.833Z"
```
Local:
```
        "bibcode": "2016pyas.confE..35R",
        "indexstamp": "2016-07-17T13:26:29.023Z"
```

Which suggests a replication problem.  @romanchyla can you please see what's happening?

**Comment by aholachek** [comment]
ok closing this as it's not a bumblebee issue then
