### ISSUE TITLE
fetch new token every 24 hours

### ISSUE THREAD

**Issue by aholachek** [adsabs/bumblebee#1053]
as far as I understand, currently if someone has a page open for more than 24 hours, no services will respond since the token is set to expire

**Comment by aholachek** [comment]
Hmm... I've had a bbb window open for 28 hours in an incognito session and it is still making requests perfectly fine. So the expiration, if it exists, has to be more than 24 hours...

**Comment by romanchyla** [comment]
as mentioned, look at the expire_in, this is what comes from bootsrap:

```
{"username": "anonymous@ads", "scopes": ["execute-query"], "access_token": "....", "token_type": "Bearer", "anonymous": true, "expire_in": "2016-08-11T18:56:46.845736", "refresh_token": "..."}
```

the time looks local, but is actually UTC; so may have to do some adjustment in the browser to get the right translation

**Comment by aholachek** [comment]
Ok so the token I requested yesterday morning is set to expire tomorrow at GMT 9pm if I understand correctly, which would mean 48+ hours before expiration.

Do you know if the refresh_token does anything? Right now as far as I can tell bbb sets it into api.js and then ignores it.

**Comment by aholachek** [comment]
instead of automatically fetching a token, it checks if the anonymous token is about to expire
