### ISSUE TITLE
export to ADS classic from a library page is broken

### ISSUE THREAD

**Issue by aholachek** [adsabs/bumblebee#1081]
console message is "apiTargets is undefined"
(other export formats work fine)

**Comment by ehenneken** [comment]
Changing `apiTargets` to `ApiTargets` in
```
https://github.com/adsabs/bumblebee/blob/master/src/js/widgets/export/widget.js#L292
```
does not seem to solve the problem entirely. I do get the correct Classic view in a separate tab (but not always), but the BBB library view gets replaced by an empty results page ("Your search returned 0 results"), while the URL remains that of the original library. I don't see an error message in the console.
