### ISSUE TITLE
Link from ORCID user page to search results lacks sort

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#1082]
The link we create from a user's ORCID page (https://ui.adsabs.harvard.edu/#user/orcid) to search results containing the user's name (in my case https://ui.adsabs.harvard.edu/#search/q=author%3A(%22Accomazzi%2C%20Alberto%22)) contains no sort, which produces a somewhat random ordering.

The sort should be "date desc"

**Comment by thostetler** [comment]
Is this still an issue? 

It seems to generate the correct url:
https://github.com/adsabs/bumblebee/blob/664d090916f65ee301ba5f515b814cb3763ffc76/src/js/modules/orcid/widget/templates/container-template.html#L25

I am unable to reproduce at the moment.
