### ISSUE TITLE
Change language for AIE

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#1084]
When displaying the graphics content we currently say it's available from the  IOP "Astronomy Image Explorer".  It should really read the AAS Astronomy Image Explorer.

**Comment by ehenneken** [comment]
This is actually not a Bumblebee issue, but a graphics database/service issue, as the text for the link is stored together with the thumbnail data in the graphics database. I'll open a ticket in the appropriate place.
