### ISSUE TITLE
Click on graphics does not change URL

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#1114]
when looking at an abstract page such as this one: https://ui.adsabs.harvard.edu/#abs/2015ApJ...815..130G/abstract

If you click on the graphics thumbnail in the right the URL does not change, whereas if you click on the "graphics" tab on the left-hand menu it correctly changes to: https://ui.adsabs.harvard.edu/#abs/2015ApJ...815..130G/graphics

**Comment by ehenneken** [comment]
That's a feature :-)
