### ISSUE TITLE
Swap "publisher article" and "publisher pdf" in page view

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#1133]
See e.g. right menu of https://ui.adsabs.harvard.edu/#abs/2015ApJS..221...35K/abstract

**Comment by Gabriel-p** [comment]
What is the issue you see here? I see that the "publisher article" points to the article and "publisher pdf" to the PDF.

**Comment by aaccomazzi** [comment]
We want the link to the online HTML version to come before the link to the PDF version, since the HTML version will provide a greater number of features than PDF.

**Comment by thostetler** [comment]
Closing, should be fixed.
