### ISSUE TITLE
Consistent error for ORCID import of J.Peek's papers

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#1140]
Josh has a list of 125 papers (as of today) in his ORCID profile: http://orcid.org/0000-0003-4797-7030

When viewing them in ADS Bumblebee throws an error:
![image](https://cloud.githubusercontent.com/assets/910261/22081317/1f65e868-dd91-11e6-8a31-1ac906206e92.png)

**Comment by romanchyla** [comment]
https://github.com/adsabs/bumblebee/pull/1141
