### ISSUE TITLE
Resort of object query causes object:XXX to turn into simbid:YYY

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#1143]
https://ui.adsabs.harvard.edu/#search/q=object%3AM87&sort=date%20desc%2C%20bibcode%20desc

If you resort, eg. by citations, you get:

https://ui.adsabs.harvard.edu/#search/q=simbid%3A1937204&sort=citation_count%20desc%2C%20bibcode%20desc

And from now on it's a simbid query

**Comment by thostetler** [comment]
This seems to be by design -> https://github.com/adsabs/bumblebee/blob/master/src/js/components/query_mediator.js#L101

**Comment by aaccomazzi** [comment]
This is not the wanted behavior though -- what we want is for the user to enter and see queries that use "object" as a search field and then translate them to "simbid" behind the scenes only.  

Whether there is a clean way to do this is a good question though...  I notice a different behavior in the UI when doing an object query vs. unfielded query followed by a constraining of the publication year range via the histogram.

**Comment by adsabs-beer-user** [comment]
I'm talking with Tim about this tomorrow

--EH

**Comment by thostetler** [comment]
This issue should now be resolved.
