### ISSUE TITLE
Papers in groups of 'Paper Network' don't add up to total?

### ISSUE THREAD

**Issue by Gabriel-p** [adsabs/bumblebee#1149]
1. Select a group of articles [from a search](https://ui.adsabs.harvard.edu/#search/fq=%7B!type%3Daqp%20v%3D%24fq_author%7D&fq_author=(author_facet_hier%3A%220%2FPichardo%2C%20B%22)&q=author%3A%22Pichardo%2C%20B.%22&sort=date%20desc%2C%20bibcode%20desc/paper-network).
1. Click on the `Paper Network` metric.
1. Save the `XX` number show in: "*Currently viewing data for `XX` papers.*"
1. Click on the auto-generated group `i` and save the `yy_i` number shown in: "*This group consists of `yy_i` papers, which have been..*"
1. Add up all the `yy_i` numbers collected for all the groups.
1. See that: `\sum yy_i != XX`

What am I missing here? Shouldn't the articles in all groups add up to the total number of articles analyzed?

**Comment by ehenneken** [comment]
Hi Gabriel

Only 65 papers of the 90 in the results set have references associated with them, so only those papers can contribute to the network. If you base the network on those 65 papers, you'll see that the numbers in each group add up to 65.

**Comment by Gabriel-p** [comment]
Of course. Don't know how I didn't think about that. Thanks!
