### ISSUE TITLE
Make abstract pages preview-friendly

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#1162]
Applications such as Twitter, Facebook and Slack use metadata embedded in web pages to generate a preview of the page itself.  We were reminded of this by one of our fans at LSST, with a link to this how-to page: https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254 

See also #792 for additional use cases of embedded metadata.

**Comment by timj** [comment]
Fantastic. Do you know when this code is planned for release?

**Comment by ehenneken** [comment]
It will be available on our development UI (devui.adsabs.harvard.edu) soon, later today. We don't have a date for releasing on production yet.

**Comment by timj** [comment]
I'm happy to try it from Slack when it's deployed to devui (it doesn't seem to work at the moment).

**Comment by aaccomazzi** [comment]
Still an issue at least for slack, see e.g. https://devui.adsabs.harvard.edu/#abs/2018NIMPA.896...24B/abstract

**Comment by thostetler** [comment]
yeah because the crawlers for slack, facebook, twitter, etc. only download html, our dynamic metatags don't get loaded.  We will have to pre-render or generate this metadata server-side in order for unfurl links to work properly.

**Comment by gpdf** [comment]
Still very interested in this.  It's really an obstacle to communicating to people by posting `adsabs` links.

**Comment by aaccomazzi** [comment]
So we are making progress on this under the hood, and we plan to release a service that creates HTML pages and caches them so that they will be crawlable and properly unfurl.  We have already released the building blocks required for this: a push-state version of the UI (which makes abstract pages URL look like this: https://ui.adsabs.harvard.edu/abs/2018NIMPA.896...24B/abstract) and a rendering/caching layer which we are currently testing (https://github.com/adsabs/turbobee).

Unfortunately the work has been delayed due to scheduling issues, but we hope to release this functionality before summer.

Feel free to leave more details on the relevant repos if you have additional thoughts.

**Comment by timj** [comment]
Am I right in thinking that this now works properly? I do see unfurling.

**Comment by aaccomazzi** [comment]
Yes, this was implemented and deployed back in September.  Thanks for the reminder and sorry for being sloppy about closing issues...
