### ISSUE TITLE
Dropdown list of OpenURL servers is not sorted alphabetically

### ISSUE THREAD

**Issue by ehenneken** [adsabs/bumblebee#1167]
The most recent additions to the list of OpenURL servers are added at the bottom of the dropdown list
![screen shot 2017-05-18 at 9 59 36 am](https://cloud.githubusercontent.com/assets/273358/26205788/cf5bea4c-3bb0-11e7-9c93-03fad81b8447.png)

**Comment by thostetler** [comment]
Issue is with the microservice that handles the OpenURL servers, not a Bumblebee issue.  Closing
