### ISSUE TITLE
Cannot Show Empty Libraries In Search Results

### ISSUE THREAD

**Issue by thostetler** [adsabs/bumblebee#1176]
Should we allow empty libraries?

If you have an empty library and you click on `View library in search results page` button it throws an error in the console and also appears to hang, like it's working.

**Comment by ehenneken** [comment]
I think we should allow empty libraries. Maybe the `View library in search results page` button can be made inactive or invisible when there are no records in a library?

**Comment by thostetler** [comment]
Yep, I'm working on that now -- It should probably work like the tabs on the same page
