### ISSUE TITLE
Page numbers missing when saving to Zotero

### ISSUE THREAD

**Issue by lbignone** [adsabs/bumblebee#1184]
Most fields (authors, title, journal, volume, DOI, date) are correctly populated when saving to Zotero but the Pages field is regularly missing.

Using: Firefox 52.0.2 (64-bit) in Ubuntu 14.04

**Comment by ehenneken** [comment]
Could you please provide us with the steps you follow to save records to Zotero? Thank you!

**Comment by lbignone** [comment]
Sure. 

I load an abstract page (for example https://ui.adsabs.harvard.edu/#abs/2016A&A...592A..93T/abstract)

Then press the "Save to Zotero" button  in the toolbar. Specifically the "Save to Zotero using 'Embedded Metadata" which I believe is the default. 

The entry correctly appears in my library, but with Pages field empty. 

As far as I can tell this happens with all abstracts.

**Comment by lbignone** [comment]
I also asked in the Zotero forums (https://forums.zotero.org/discussion/comment/277532#Comment_277532). 

One of the developers responded this:

> Currently we just import the standard metadata from the page and that doesn't include the page number. It'd be great if ADS could fix that (specifically, add citation_firstpage and citation_lastpage metatags).
> There are various things we can do otherwise, but always easiest to have this working without dedicated Zotero code.

**Comment by ehenneken** [comment]
Thanks for the detailed information!

**Comment by adam3smith** [comment]
feel free to tag me with any Zotero-related questions

**Comment by ehenneken** [comment]
@lbignone This has now been fixed in our development environment. It will be activated in production after the next release. We will let you know when that will happen.

**Comment by ehenneken** [comment]
The fix is now active in production.

**Comment by adam3smith** [comment]
This is great, but is there any reason you only added `citation_firstpage`? E.g.
https://ui.adsabs.harvard.edu/#abs/2017NewA...57....6S/abstract has a page range 6-13 that shows up e.g. in the BibTeX, but I'm only seeing the `citation_firstpage` metatage (and so Zotero imports the page range as 6 rather than 6-13

**Comment by ehenneken** [comment]
The reason is that the last page is not yet available in the records in our index. We are working on adding more fields to our Solr documents, so we will add more metadata to our abstracts as it becomes available.
