### ISSUE TITLE
Link to authors in 'Show all authors' drop down list is broken

### ISSUE THREAD

**Issue by Gabriel-p** [adsabs/bumblebee#1200]
Try clicking on some the authors of this article:

https://ui.adsabs.harvard.edu/#abs/2017ApJ...838L..14M/abstract

In my case, I see that for approx half of them at first it tries to perform the search but then quickly falls to

https://ui.adsabs.harvard.edu/#

**Comment by taylorshaulis** [comment]
Every author that loaded from the "..." just takes me back to the bumblebee landing page. 

A link that works 

`<a href="#search/q=author%3A%22Bonatto%2C+Charles%22&amp;sort=date+desc">Bonatto, Charles</a>`

A link that does not work

`<a href="#search/?q=author%3A%22Majaess%2C+Daniel%22&amp;sort=date+desc">Majaess, Daniel</a>`

The only difference I see is the ? added at the start of the query.
