### ISSUE TITLE
Sort By Normalized Citations

### ISSUE THREAD

**Issue by thostetler** [adsabs/bumblebee#1275]

**Comment by thostetler** [comment]
@aaccomazzi I noticed some of the pipeline citation_count_norm tickets were done, is this one ready to go?

**Comment by spacemansteve** [comment]
@thostetler The pipeline code is done, perhaps by the end of the week we will have populated the field in a Solr instance.

**Comment by thostetler** [comment]
Alrighty that sounds good, thanks!

**Comment by aaccomazzi** [comment]
This is ready to go, all it needs are the sort options and labels: 
* "citation_count_norm desc" 
* "citation_count_norm asc" 

Label is "Normalized citation count"
