### ISSUE TITLE
Query ending with "review" word triggers reviews() auto-complete

### ISSUE THREAD

**Issue by marblestation** [adsabs/bumblebee#1301]
When querying "review" in BBB, the auto-complete converts it to reviews() and it can be frustrating deleting and pressing enter again (and sometimes triggering the auto-completion once again). Review is a word that can be popular among astronomers since there are many paper that offer reviews of a given subject.

**Comment by thostetler** [comment]
I agree with this, but I wonder how to make it better.  For example I have trouble with chrome auto-filling urls when I start typing in the search bar.  
Currently, it does let you backspace to clear the suggestion, should we make an example of "review" and stop it from autocompleting until say "reviews("?

**Comment by aaccomazzi** [comment]
Auto-complete is both a blessing and a curse, but it leaves it up to the user to accept or reject it.  The only case in which "review" turns into "reviews()" in my browser (latest chrome) is if I hit return while the suggestion is being offered.  If I add a space or any other character after the "w" in review then the suggestion goes away.  Unless somebody can think of a better way to handle this, I don't think we should do anything.

**Comment by adsabs-beer-user** [comment]
Maybe just add longer wait/delay (200ms) ?

**Comment by thostetler** [comment]
I am seeing, however that if you paste in a string with `review` it does add the auto-complete.  I agree with delaying, if it was pasted we probably don't want auto-complete.

ex: `space review` -> `space reviews()`

**Comment by marblestation** [comment]
With the current behavior, auto-complete is not suggesting but imposing a completion by default which get on the way of a users typing. 

What do you think of auto-completion that suggests options and by default it does not auto-complete anything? The UI could show exactly the same list of options as now but with an added first element that would be empty and selected by default. Meaning:

- "review<enter>" => you search "review" (submit)
- "review<down><enter>" => you auto-complete "reviews()" and you can continue typing until you submit
- "author<down><enter>" => you auto-complete "author:""" and you can continue typing until you submit
- "author<down><down><enter>" => you auto-complete "author:"^"" and you can continue typing until you submit

Oh, I have just noticed that what I'm proposing it kind of exists already but it is not the default and it is a bit hidden:

- "review<down><down><enter>" => it already does search "review" (submit) and it does not auto-complete

But as you can see, it is not the default behavior and it is not obvious/intuitive to find this option. Hence, we could make it default and/or make it more obvious. Personally, I would prefer auto-complete not to be the default behavior (I think it facilitates transition to BBB and makes you less angry).
