### ISSUE TITLE
Parsing of "( foo)" generates an error

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#1358]
### Expected Behavior
A search of `( foo)` should be treated the same as a search for `(foo)`

### Actual Behavior
Rather than sending the query along to SOLR, BBB generates an error message: ` Sorry! We aren't able to understand: (`

This suggests that BBB does more parsing of the query string than we may want...

**Comment by thostetler** [comment]
It does seem to get through to solr
I'm getting an error: 
```
{
  "metadata": [
    "error-class",
    "org.apache.solr.common.SolrException",
    "root-error-class",
    "java.lang.Exception"
  ],
  "msg": "org.apache.solr.search.SyntaxError: INVALID_SYNTAX_CANNOT_PARSE: Syntax Error, cannot parse ( : The parser reported a syntax error, antlrqueryparser hates errors! ",
  "code": 400
}
```
Does it make it through if you try it directly on solr?

**Comment by thostetler** [comment]
nevermind, I can confirm this is an issue with how BBB validates queries.
