### ISSUE TITLE
Expanding an author list longer than default in Citations view doesn't work

### ISSUE THREAD

**Issue by seasidesparrow** [adsabs/bumblebee#1428]
### Expected Behavior
For each paper in the citations list where the author field length exceeds the default displayed length, there is a link with text "and [#] more" where # is the number of authors not shown.  Clicking this should return a list of additional authors.

### Actual Behavior
Clicking this list does not show the author.  It erases the entire author field, and returns only the link "Show less" with no author metadata.  The same behavior is seen in both Safari and Firefox.

### Steps to Reproduce

* Go to https://qa.adsabs.harvard.edu/#abs/2004JAVSO..32...41T/citations
* Under the first citation, click the "and 7 more" link.
* The proper behavior is seen when you go to the "view this list in a search results page" link and click the same link.

**Comment by thostetler** [comment]
Nice catch!

**Comment by thostetler** [comment]
Fixed in #1429
