### ISSUE TITLE
Stuck at the loading page.

### ISSUE THREAD

**Issue by gapplef** [adsabs/bumblebee#1504]
I try to use the new ADS,  but it always stuck at the loading page.
![screenshot from 2018-06-07 10-26-18](https://user-images.githubusercontent.com/5604665/41075047-643955d0-6a3d-11e8-815e-af88a8f6e654.png)
![screenshot from 2018-06-07 10-26-27](https://user-images.githubusercontent.com/5604665/41075049-64753050-6a3d-11e8-845e-89663fbbefbf.png)

**Comment by thostetler** [comment]
Hi @gapplef, sorry about the issue -- can you provide some more details here, if this is still happening for you.  
Do you have any errors in the dev console? 
and what browser/OS are you running?

**Comment by gapplef** [comment]
I got the following error message
```
Loading failed for the <script> with source
“https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js”.
```
This may be due to the network.
I'm in China, where `ajax.googleapis.com` is blocked.

And I'm using Firefox on Ubuntu 16.04/18.04

**Comment by thostetler** [comment]
Ah okay, sorry about the access issue! I'll make a ticket to review our CDNs to make sure the site is accessible from alternate sources.
