### ISSUE TITLE
"Back to results" shows infinite spinning wheel

### ISSUE THREAD

**Issue by marblestation** [adsabs/bumblebee#1556]
### Expected Behavior

"Back to results" button should go back to the result view and show the last results.

### Actual Behavior

"Back to results" button goes back to the result view and an infinite spinning wheel is shown.

### Steps to Reproduce

1. Search anything
2. Click on any title
3. Click "Back to results" button in the web (not the browser's back result)

**Comment by thostetler** [comment]
Yeah this behavior is probably only in QA and DEV, its a regression from the sorting bug.  I should have a fix coming shortly.
