### ISSUE TITLE
Missing library link in abstracts

### ISSUE THREAD

**Issue by marblestation** [adsabs/bumblebee#1650]
### Expected Behavior

When a user selects a library link server, the corresponding link should appear in the abstracts.

### Actual Behavior

When a user selects a library link server, the corresponding link does not appear in the abstracts.

### Steps to Reproduce

1. Authenticate and make sure you have selected a library in Accounts > Customize Settings > Library Link Server
2. Go to https://ui.adsabs.harvard.edu/#abs/2019MNRAS.482.1786L/abstract
3. No library link server appears on the right side

**Comment by thostetler** [comment]
Do you have any other examples? this one is actually not showing it because it the resources contain a link with OPEN access.  I'm able to get the icon to show if I remove OPEN_ACCESS from property for example.

**Comment by thostetler** [comment]
After discussion, the library links should be created when there isn't a PUBLISHER open access link, instead of a general one.  I'll make that fix.
