### ISSUE TITLE
Unnecessary "Volume Content" links in abstract pages

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#1653]
Many records seem to have TOC links (aka "Volume content " links) when they shouldn't.
For example, `2018arXiv181112640R` has such a link, even though there is no TOC property in the record.  I'm not sure what is being used as the current business logic.

The expected behavior and data to be used is described here: https://github.com/adsabs/bumblebee/issues/1265
but @golnazads may want to confirm that this is still up to date.

**Comment by golnazads** [comment]
My understanding is that TOC is set in solr according to data read from
https://github.com/adsabs/AdsDataSqlSync/blob/master/config.py#L29
@spacemansteve am I correct?

**Comment by marblestation** [comment]
I don't see the described behavior using the example bibcode (no TOC link is showed): https://ui.adsabs.harvard.edu/#abs/2018arXiv181112640R/abstract

**Comment by aaccomazzi** [comment]
See the "Volume Content" link on the left bar

![image](https://user-images.githubusercontent.com/910261/49510009-0d121e80-f855-11e8-959d-1c6280b7de0c.png)

**Comment by thostetler** [comment]
fixed in https://github.com/adsabs/bumblebee/pull/1709
