### ISSUE TITLE
Sort Not Getting Updated By Fielded Searches

### ISSUE THREAD

**Issue by thostetler** [adsabs/bumblebee#1664]
Certain fields, such as `similar` should apply a specific sort to the query.  This is not working currently.

**Comment by thostetler** [comment]
@aaccomazzi what is the sort for `similar`? and do you know of any other ones that aren't working? for some reason I didn't actually put any detail into this ticket after we mentioned it during the meeting.

**Comment by aaccomazzi** [comment]
sort by "score desc"

**Comment by thostetler** [comment]
was fixed by https://github.com/adsabs/bumblebee/pull/1695
