### ISSUE TITLE
sort order of records is ignored in export

### ISSUE THREAD

**Issue by ehenneken** [adsabs/bumblebee#1670]
### Expected Behavior
A results list is generated in a particular sort order. When exporting records in a certain format, it is expected that this sort order is maintained
### Actual Behavior
The sort order is different in the exported list
### Steps to Reproduce
1. Generate a list of records: `references(bibcode:2018MNRAS.479.1017R)`
2. Sort by first author
3. Export in custom format: `%g %T // %J.%Y.Vol. %V. P. %p-%P.`
4. It looks like records are now sorted by date, descending

**Comment by golnazads** [comment]
Yes, if sort order is not send to export service, the default is sort by date descending.

Note that there is an optional parameter sort for sorting the records from solr. The default sort option (if omitted) is by date desc, bibcode desc. For example

From readme
curl -H "Authorization: Bearer <your API token>" -H "Content-Type: application/json" -X POST -d '{"bibcode":["2015ApJS..219...21Z", "2018AAS...23221409A"], "sort":"bibcode desc"}' https://api.adsabs.harvard.edu/v1/export/bibtex
