### ISSUE TITLE
Author query from abstract page does not remove previous bulk query

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#1683]
### Expected Behavior
When looking at an abstract page, a click on an author name should generate a list of results determined solely by the author query (e.g. `author:"accomazzi, alberto"`)

### Actual Behavior
The author query generated from abstract page selected from a result list which included a bulk query pill will show results constrained by the bulk query

### Steps to Reproduce
1. Search for `author:"accomazzi, a"`
2. select "author network"
3. click on the biggest wedge of the diagram, then "add to filter", then submit
4. on the resulting list you should see a "bulk query" pill in the search box.  Click on any abstract link
4. in the abstract page, click on any author name (e.g. "Grant, C. S.")
5. the resulting list of results will still have the "Bulk query" pill in the search box

**Comment by thostetler** [comment]
@aaccomazzi so this is an explicit thing that happens just before the search executes: https://github.com/adsabs/bumblebee/blob/master/src/js/components/query_mediator.js#L237

Should the bigQuery be dropped any time we have a new query coming in? or is it common to augment it instead?

**Comment by aaccomazzi** [comment]
We should keep the original bigquery if and only if the user modifies the query in the search bar, but in this instance we are generating a brand new query from an author name link, so the bigquery filter has to go.

BTW this also applies to the case where one clicks on e.g. the list of co-reads, then on "View this list as search results page."  This is a new search, so the bigquery box needs to go.

**Comment by thostetler** [comment]
alrighty, that makes sense to me -- I will work on that change
