### ISSUE TITLE
Right-column year filter breaks unfielded author searches

### ISSUE THREAD

**Issue by kelockhart** [adsabs/bumblebee#1685]
### Expected Behavior
1. Search for `accomazzi, alberto` - search results are returned
2. Use the year sliders in the right column to restrict the date range
3. Click Apply to restrict the search results - the year-restricted results should be returned
### Actual Behavior
At step 3 above, this error is returned: `Sorry no results were found for (accomazzi, alberto AND year:1995-2018)`, though there are records that match the search parameters. Ideally, the parentheses that wrap the search results after applying the year filter should only be wrapped around the original query, not the original query and year filter as is done now.

**Comment by aaccomazzi** [comment]
So application of the facet should yield:
```
(accomazzi, alberto) AND year:1995-2018
```
i.e. wrap the original query with parenthesis rather than what we do now

**Comment by thostetler** [comment]
Duplicate: #1712
