### ISSUE TITLE
Do not allow empty library names

### ISSUE THREAD

**Issue by marblestation** [adsabs/bumblebee#1686]
### Expected Behavior

Do not allow creation of a new library if the name is not provided. Some users are clicking the button by mistake, when they really wanted to click the button that adds the papers to a concrete already existing library.

### Actual Behavior

It creates a new library if the name is not provided with the name "Untitled Library 1".

### Steps to Reproduce

1. Search anything
2. Select some articles
3. Add to library and just press the second submit button

**Comment by aaccomazzi** [comment]
While we are discussing this, I think we had a related good suggestion from a user: the selection of the library to add results to should default to the last selected library, rather than the first in alphabetical order.
