### ISSUE TITLE
Merge buttons for adding to an existing library + create a new library

### ISSUE THREAD

**Issue by marblestation** [adsabs/bumblebee#1687]
### Expected Behavior

The user should select from the dropdown list if (s)he wants to add things to an existing library or a new one (allowing the user to type in the new library name, only if (s)he selected that option).

### Actual Behavior

Two buttons are shown, the first one is related to a dropdown list with the list of existing libraries while the second one is related to an input text box where the user can specify a new library name. Some users make frequently the mistake of pushing the second submit button when they meant the first. Improving the UI should reduce these mistakes.

### Steps to Reproduce

1. Search anything
2. Select some articles
3. Add to a library

**Comment by aaccomazzi** [comment]
Here we get into the UXy kind of stuff where I feel somewhat insecure.  But for sure, we could disallow the second "submit" button if the name of a new library is not filled in
