### ISSUE TITLE
Change "Export" label in abstract view

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#1692]
A couple of users have mentioned that "Export" is not an intuitive label for getting bibtex, aastex, etc. output when one is viewing an abstract page.

Some alternatives:
1. "Cite as" (used by Zenodo)
2. "Export Citation" (used by APS)

I personally favor the latter.

**Comment by thostetler** [comment]
I like "Cite as" as well -- should this be the naming used on the results and libraries page as well? 

And if so, should we think of somewhere else to put that Author Affiliation tool?

**Comment by aaccomazzi** [comment]
No, we should leave the "Export" for the list of results because a lot of the other formats and the author-affiliation tool really are export functions.

I still favor "Export citation" over "Cite as" but let's see what other people think
