### ISSUE TITLE
List of libraries empty with misleading message when HTTP status code != 200

### ISSUE THREAD

**Issue by marblestation** [adsabs/bumblebee#1699]
### Expected Behavior

When GET to `https://dev.adsabs.harvard.edu/v1/biblib/libraries` returns 404, an error should be shown to the user which should not lead the user to think that he has no libraries at all. This causes panic to the users, they think they have lost their data when in reality there was just a communication problem (or pods in kubernetes were behaving badly).

### Actual Behavior

When GET to `https://dev.adsabs.harvard.edu/v1/biblib/libraries` returns 404, this is shown:

"You don't have any libraries yet!

Search ADS to find papers that you want to add."

### Steps to Reproduce

- Go to the user libraries
- The misleading message will appear if a 404 is received for `https://dev.adsabs.harvard.edu/v1/biblib/libraries`

**Comment by thostetler** [comment]
Fixed in https://github.com/adsabs/bumblebee/pull/1704
