### ISSUE TITLE
Create link for "Similar records" in abstract view

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#1703]
We now have the `similar()` operator so we should add the option to find similar records when a user views an abstract page.

I would suggest putting this link right below the coreads, but since it's a computationally expensive result, we should *not* precompute this for every abstract that gets loaded (the same should apply to coreads).  The resulting list (as well as the results from coreads) should be sorted by `score desc` .

**Comment by thostetler** [comment]
Done in https://github.com/adsabs/bumblebee/pull/1709
