### ISSUE TITLE
Enable firefox's keyword shortcut in home page

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#1711]
### Expected Behavior
When on the home page with FF, right clicking and selecting "Add a Keyword for this search" allows one to create a shortcut so that you can type in the browser's search bar something like "ads accomazzi" to run an ADS query.  This works with ADS classic (try going to http://adsabs.harvard.edu and doing so in the one-box search bar)

### Actual Behavior
Following this process in BBB creates search URLs of the kind: https://ui.adsabs.harvard.edu/?q=accomazzi which do not run a query.  There must be a parameter in the search form that should be set to point to the search URL instead (if you do this in classic the URL that is created looks like this: http://adsabs.harvard.edu/cgi-bin/basic_connect?qsearch=accomazzi&version=1)

### Steps to Reproduce
Go to https://ui.adsabs.harvard.edu, right click on the search box, select "Add a Keyword for this search", assign it the keyword "ads", then type "ads accomazzi" in the browser's bar.

**Comment by thostetler** [comment]
Yeah this just needs the form to have an action, right now that is handled within backbone.
