### ISSUE TITLE
applied filter is messing up query semantics

### ISSUE THREAD

**Issue by romanchyla** [adsabs/bumblebee#1712]
### Expected Behavior

we have to be careful when modifying a query (or even when adding conditions); because operators influence how the whole thing gets parsed

the safest way to prevent problems is to wrap user's query in brackets

`A, maury` -> `(A, maury ) AND year:1847-1900`

### Steps to Reproduce

1. search for `A, maury`
2. on the histogram, select years 1847-1900 and hit apply
3. zero hits are found because the query is `A, maury AND year:1847-1900`

**Comment by aaccomazzi** [comment]
Related to this: currently subsequent year range selections mess up the query even further.  Try the following:

1. Search for `accomazzi`
2. Apply start year selection by moving the left slider to "2000" and click on "Apply", the query becomes `(accomazzi AND year:2000-2019)` (as discussed above this should be changed to be `(accomazzi) AND year:2000-2019`
3. Apply end year selection by moving the right slider to "2010" and click "Apply", the query becomes `"(accomazzi AND year:2000-2019 AND year:2000-2010)"` which is clearly wrong
4. Interestingly, I notice a bunch of URL values being added named `__year_q` and wonder why we need them?

**Comment by romanchyla** [comment]
Those underscore values are secret for successfully modifying the query. If
used properly, with query_updater, just the year query portion will get
updated
