### ISSUE TITLE
Implement user-selectable bibtex key format

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#1845]
As described in this issue: https://github.com/adsabs/export_service/issues/93,
we want to enable the creation of bibtex output where the key is customized to be in a particular format (typically a combination of first author's last name and publication year).  This requires three parts:

1. Adding a preference to the user database where the user can specify his/her preferred format (typically something like `%2H%Y`).  The default should be the current one, which is `%R`, i.e. the bibcode of the record
1. Updating BBB's user preference menu to allow the user to view/modify this optional preference 
1. Enabling the requested functionality in the export service as an option -- this means BBB should pass the bibtex key format along with the requested option

So this needs coordination from @golnazads @kelockhart and @thostetler

**Comment by golnazads** [comment]
from export_service readme
```
Note that for endpoints /bibtex and /bibtexabs optional parameters maxauthor and keyformat can be passed in. maxauthor is maxinum number of users displayed. The default values for maxauthor for /bibtex and /bibtexabs respectivley are 10 and 0, where 0 means all. keyformat allows user to customize bibtex key and could contain some combination of authors' last name(s), publication year, journal, and bibcode. User is now able to pick the key generation algorithm by specifying a custom format for it. 
```
