### ISSUE TITLE
BBB cannot find authors with a space in their last name

### ISSUE THREAD

**Issue by hsgg** [adsabs/bumblebee#1861]
The [new ADSABS](https://ui.adsabs.harvard.edu) interface can no longer search for authors with a space in their last name (I assume the space is the culprit?). For example a search `^"Grasshorn Gebhardt"` results in

    Something Went Wrong
    Please Retry Your Search

The [old interface](http://adsabs.harvard.edu/) has no problems with this.

**Comment by csgrant00** [comment]
Without any context, "Grasshorn Gebhardt" is assumed to be "first name last
name".
Try author:"Grasshorn Gebhardt, H"

-Carolyn

*************************************************************************

 Carolyn Stern Grant              Astrophysics Data System (ADS)

 cgrant@cfa.harvard.edu        Center for Astrophysics

 617-495-7154 (voicemail)      60 Garden Street  MS 83

 617-495-7356 fax                 Cambridge, MA  02138

*************************************************************************

**Comment by hsgg** [comment]
> Try author:"Grasshorn Gebhardt, H"

Is there a less verbose option?

**Comment by shinyichen** [comment]
The search by author should be either `author:"Grasshorn Gebhardt"` or `author:"^Grasshorn Gebhardt"`
`^"Grasshorn Gebhardt"` is not a valid search
