### ISSUE TITLE
Strange rendering for https://ui.adsabs.harvard.edu/abs/2019A%26A...628L...6V/abstract

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#1905]
For the abstract: https://ui.adsabs.harvard.edu/abs/2019A%26A...628L...6V/abstract

The pubnote field shows incorrect rendering of its (html-encoded) content, as if we are breaking on semicolon?  We should just display content as-is.

**Comment by thostetler** [comment]
Yeah it tries to split on `;` in order to spread out onto separate lines.  I'll remove that and dump it out as a raw string.

**Comment by thostetler** [comment]
![image](https://user-images.githubusercontent.com/6970899/63286947-2a720600-c287-11e9-9c2f-26844bc62e25.png)

**Comment by thostetler** [comment]
![image](https://user-images.githubusercontent.com/6970899/63286981-3b227c00-c287-11e9-92ec-16b3757e19d7.png)

**Comment by aaccomazzi** [comment]
Hmmm... the HTML encoding is still showing ("&amp;amp;" rather than "&").  The data in SOLR is encoded already, so you'd want to find a way to disable the re-encoding of it...

**Comment by thostetler** [comment]
Sure, I will add an update to unescape these HTML entities.  Btw it does look like its coming from Solr this way already, unless that is what you were saying.  
![image](https://user-images.githubusercontent.com/6970899/63293554-55b02180-c296-11e9-9ba8-fff56bf99221.png)
