### ISSUE TITLE
Fix second operator sort order when multiple operators found in query

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#2045]
Right now BBB sets its sort based on the detection of second order operators in the query in the following way:
```
reviews() -> score
references() -> first author
```
When combining multiple operators, it looks like the sort is determined by the last (in alpabetical order) of the operators found in the query.  This means that a query such as `reviews(references())` will sort by first author.  What we should do is to always apply the sort associated with the outer operator (in this case `reviews()`).

I assume we use the `indexOf()` method to find if an operator is present in the query.  In this case, we should select the operator with the smallest index greater than -1 and then set the sort order associated with it.

**Comment by thostetler** [comment]
Fixed in #2048
