### ISSUE TITLE
Don't escape content coming back from text snippets

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#2084]
The text highlights show HTML markup, rather than a properly rendered version of the contents.  This is probably because the application does not display the contents as straight HTML but rather escapes them.

Example query: `effects bibcode:2020ApJ...901L..36Z` (see screenshot below)

![image](https://user-images.githubusercontent.com/910261/99544698-99ef0d80-2982-11eb-8ff7-014fd11bfb67.png)

**Comment by shinyichen** [comment]
Addressed in PR https://github.com/adsabs/bumblebee/pull/2166
