### ISSUE TITLE
ADS Libraries does not load when analytics.js is blocked

### ISSUE THREAD

**Issue by jwuphysics** [adsabs/bumblebee#2097]
### Expected Behavior
When opening a public ADS library, for example, [one of mine](https://ui.adsabs.harvard.edu/public-libraries/cEIZdS8tReiOS8sKk7LR7g), the page should load even if a browser plugin (such as uBlock origin) is blocking Javascript or Google analytics. This may be related to #1160.

### Actual Behavior
The page hangs at "Downloading Assets" and does not load further:

![image](https://user-images.githubusercontent.com/3582121/102840304-8e9f5f80-43d0-11eb-9fd2-c0c989dd87a5.png)

### Steps to Reproduce

1. Open a browser (I tested Chromium and Firefox on Linux) and install/enable uBlock Origin.
2. Navigate to a public ADS library, e.g., https://ui.adsabs.harvard.edu/public-libraries/cEIZdS8tReiOS8sKk7LR7g.
3. Observe that the page gets stuck at loading (see image above).
4. Note that opening the console (F12) reveals a few errors, including these:
```Loading failed for the <script> with source “https://ui.adsabs.harvard.edu/js/components/analytics.js?v=v1.2.84”.

Uncaught Error: Script error for: analytics
http://requirejs.org/docs/errors.html#scripterror
    makeError https://ui.adsabs.harvard.edu/libs/requirejs/require.js:163
    onScriptError https://ui.adsabs.harvard.edu/libs/requirejs/require.js:1666
    load https://ui.adsabs.harvard.edu/libs/requirejs/require.js:1868
    load https://ui.adsabs.harvard.edu/libs/requirejs/require.js:1624
    load https://ui.adsabs.harvard.edu/libs/requirejs/require.js:825
    fetch https://ui.adsabs.harvard.edu/libs/requirejs/require.js:815
    check https://ui.adsabs.harvard.edu/libs/requirejs/require.js:845
    enable https://ui.adsabs.harvard.edu/libs/requirejs/require.js:1142
    enable https://ui.adsabs.harvard.edu/libs/requirejs/require.js:1496
    enable https://ui.adsabs.harvard.edu/libs/requirejs/require.js:1127
    bind https://ui.adsabs.harvard.edu/libs/requirejs/require.js:129
    each https://ui.adsabs.harvard.edu/libs/requirejs/require.js:57
    enable https://ui.adsabs.harvard.edu/libs/requirejs/require.js:1089
    init https://ui.adsabs.harvard.edu/libs/requirejs/require.js:779
    localRequire https://ui.adsabs.harvard.edu/libs/requirejs/require.js:1412
    setTimeout handler*req.nextTick< https://ui.adsabs.harvard.edu/libs/requirejs/require.js:1740
    localRequire https://ui.adsabs.harvard.edu/libs/requirejs/require.js:1401
[...]
  ```
5. Refreshing the page will cause it to become blank.
6. Disable uBlock Origin and refresh the page.
7. The page loads without a problem. However, the console will still display these errors.

**Comment by thostetler** [comment]
@jwuphysics thanks for the rerport! I can reproduce.  I suspect it's the fact that the file name is "analytics" which the extension automatically filters.  
Plus, I can get it to load properly if I add `ui.adsabs.harvard.edu` as a trusted site.

The fix would probably be just to bundle this file or maybe just change the name.
