### ISSUE TITLE
Selecting results off by one

### ISSUE THREAD

**Issue by thostetler** [adsabs/bumblebee#2150]
### Expected Behavior
Clicking the select all checkbox should then show the correct number selected.
### Actual Behavior
for 25 per page, the selection reports "25 records selected"
for any other, it is one under: "49 records selected" and "99 records selected"

![image](https://user-images.githubusercontent.com/6970899/115898148-3aae9100-a42b-11eb-8e19-ce634eb0829f.png)

It looks like number 25 and 26 are duplicated: 
![image](https://user-images.githubusercontent.com/6970899/115900791-58312a00-a42e-11eb-9cfc-93cf41cd6677.png)

![image](https://user-images.githubusercontent.com/6970899/115898122-32565600-a42b-11eb-8160-d135696d0df2.png)

**Comment by shinyichen** [comment]
Has it been fixed already? I am not seeing this problem

**Comment by thostetler** [comment]
Yep I can no longer replicate. I'll close.
