### ISSUE TITLE
We currently don't display the book_author field in BBB

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#2219]
We currently don't display one metadata record that is available in certain SOLR document called `book_author`.  I suggest we display it after the "Publication" field in the abstract detail page.

We should discuss priorities with @marblestation

**Comment by thostetler** [comment]
@aaccomazzi do you have an example record with `book_author`?

**Comment by aaccomazzi** [comment]
https://ui.adsabs.harvard.edu/abs/1957Sci...126.1021C/abstract
