### ISSUE TITLE
Increase limits of papers in metrics

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#255]
By default we return metrics for 20 papers, quite a meager amount.  Let's bump that up to 200.
The max is now set to 175, also way too low.  Let's make it 2,000.  Otherwise I find myself going back to ADS 2.0 for checking the metrics.

**Comment by romanchyla** [comment]
max is not 175, 175 is only the max numbers for author:accomazzi ;-)

but i'll bump the default, the metrics is snappy - so it looks it can handle it

**Comment by romanchyla** [comment]
set default to 200, max to 3000
