### ISSUE TITLE
Selected articles in result list ignored by export/explore functions

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#288]
If one or more papers have been selected by the user via the checkboxes, we need to apply the export/explore options to them rather than the top N papers.

**Comment by romanchyla** [comment]
I've just pushed #297 - this branch add functionality to select papers and these are then pushed into the app-storage; If the widget needs to work with just the selected papers, it can do:

this.getBeeHive().getObject('AppStorage').getSelectedPapers()

that should help with this issue
