### ISSUE TITLE
Implement SIMBAD facets and searches

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#290]
This is a fairly sizable task, which needs discussion with @romanchyla about what architecture to use for sure.  I'm creating an issue so we don't forget.

**Comment by ehenneken** [comment]
This is how I think the Object Search will work: format `object:(Andromeda AND (LMC OR SMC))`

What happens next?
1. Search widget sends "Andromeda", "LMC" and "SMC" to `objects` endpoint of the API, submitting `{"objects":["Andromeda", "LMC", "SMC"]}`
2. The object service micro service returns `{"LMC":{"canonical":"LMC", "id": 12345}, "SMC":{"canonical": "SMC", "id":345345}, "Andromeda":{"canonical":"ANDROMEDA", "id":5646765}}` (no, these aren't the true SIMBAD identifiers for these objects)
3. The SIMBAD identifiers from the micro service response (if any) are then used to retrieve those Solr documents that have them in their `simbid` field, matching the search logic specified in the search
4. The list of matching records is displayed

Note: if I specify non-canonical object names in my search, I will see their canonical equivalent back in the SIMBAD objects facet.

**Comment by ehenneken** [comment]
This functionality has been implemented (including unittests)
