### ISSUE TITLE
MPECs being divided by first author

### ISSUE THREAD

**Issue by donnat** [adsabs/bumblebee#295]
For example:  search for first author Herald, D.  In list of publications there appears MPEC.....L, MPEC.....O, etc.  Doesn't need to be distinguished more than MPEC.

**Comment by romanchyla** [comment]
This is more of data problem; do you have an idea of a rule that would describe situations in which the bibcode should be truncated?

**Comment by aaccomazzi** [comment]
This is an issue with ADSimportpeline, now filed as https://github.com/adsabs/ADSimportpipeline/issues/87
