### ISSUE TITLE
Publication Year as Histogram

### ISSUE THREAD

**Issue by astrodsg** [adsabs/bumblebee#300]
I was searching using bumblebee and one feature I saw missing (compared to ADS2.0) was a histogram of the publication date. I thought this was a great tool for narrowing down papers when you have something like Author name and year.

Enhancement Proposal : include in bubblebee the year histogram for current list of publications from the filter

**Comment by adsabs-beer-user** [comment]
The date histogram is still there to the right of the search results.  Is
it missing elsewhere where you expected it to be?

Thanks for writing to us.
Donna

On Fri, Mar 13, 2015 at 4:57 PM, astrodsg <notifications@github.com> wrote:

> I was searching using bumblebee and one feature I saw missing (compared to
> ADS2.0) was a histogram of the publication date. I thought this was a great
> tool for narrowing down papers when you have something like Author name and
> year.
>
> Enhancement Proposal : include in bubblebee the year histogram for current
> list of publications from the filter
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adsabs/bumblebee/issues/300>.
>



-- 
Donna Thompson
Astrophysics Data System
Smithsonian Astrophysical Observatory
60 Garden Street, MS 83
Cambridge, MA 02138
(617)496-7660
dthompson@cfa.harvard.edu

**Comment by astrodsg** [comment]
Hi Donna,

My mistake. I had the window size < 990px which hide the histogram. Putting
it in the side bar with the author+ options (maybe for <990px) could be an
improvement; but I leave that to your judgement. Cheers

**Comment by aholachek** [comment]
The bar chart now floats to the left on tablet sized interfaces.
