### ISSUE TITLE
Change URL in metadata exported to ORCID

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#309]
We should not use the following URLs when exporting data to ORCID:
http://adsabs.harvard.edu/cgi-bin/nph-data_query?bibcode=2015AAS...22533655A&link_type=ARTICLE

These only work when there is fulltext available from somewhere, but that's not the case across the board.  We should export DOIs (which we don't seem to be doing now).

**Comment by romanchyla** [comment]
the orcid module was ready for dois, but the results widget was not sending dois; i fixed that and made code to fail back to https://ui.adsabs.....#abs/BIBCODE link
