### ISSUE TITLE
Properly manage non-ADS ORCID claims in BB

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#311]
Right now it looks like none of the non-ADS records are properly reconciled with existing ADS records, which is a problem.  We should, at a minimum:

1. match on DOIs
2. match on arXiv ids (we need to find an example for this though)

To be considered: we should give users the option of "Adding to ADS" a record not recognized.  This would be a really neat option for our users.  But if we don't do this right, we may be flooded by duplicate entries, so beware...

**Comment by romanchyla** [comment]
right now the orcid api searches using bibcode, alternate_bibcode, doi; the stuff is diferentiated visually (the are that is normally green for ADS recs, is now grey; the actions are different; the caption is also different)
