### ISSUE TITLE
http://localhost:8000/#search/q=identifier%3A2014M%26PS..tmp..118C&sort=date+desc

### ISSUE THREAD

**Issue by romanchyla** [adsabs/bumblebee#369]
loading this page fails, the backbone is parsing unencoded string, which cannot be parsed by the api-query; i'm not sure how i arrived to this result, something must be setting the url inproperly, because when we call apiQuery.url() - this method makes sure that the url is properly (double) encoded so that backbone cannot interfere with it

most likely, some of the navigator methods are setting the bibcode directly into the url, not using url() call

**Comment by aholachek** [comment]
this works now
