### ISSUE TITLE
Metrics view for single paper

### ISSUE THREAD

**Issue by ehenneken** [adsabs/bumblebee#374]
The metrics view for a single paper really should show a subset of all available metrics data. Many metrics components have little meaning for a single paper (like all indicators and time series). The time series even have something curious when displayed for one record: repeated values on the Y axis (see e.g. 1994GPC.....9..143K)

The metrics view for one record really should be like the one we show in BEER (content-wise).

**Comment by romanchyla** [comment]
oh, we used to have metrics for one paper, but not sure if it was content0wise equal to beer; now i see them gone; ping ping

http://hourly.adslabs.org/#abs/2014A&A...571A..16P/abstract

**Comment by aholachek** [comment]
I wanted to put it below the abstract, since its only max 2 graphs
I can do it today...

**Comment by aaccomazzi** [comment]
Just a reminder that it would be nice to have this for the IAU.
