### ISSUE TITLE
Use `/#/` for more elegant URLs

### ISSUE THREAD

**Issue by vsudilov** [adsabs/bumblebee#393]
If we are set on not using pushState, then I think the URLs would be more elegant if they were prefixed with `/#/` instead of `/#`

**Comment by aaccomazzi** [comment]
Can we talk about this?  I feel ignorant about the pros and cons of pushState, and still clueless as to why we aren't using it.  

Related to this topic are a number of issues related to our url patterns, including: bookmarking urls, allowing crawlers and applications to get to this content, etc.  See also #345
