### ISSUE TITLE
bug in limit by year, citations, reads

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#404]
If you have a query which contains an or such as "ack:NASA or aff:NASA" and then use the citation tab to limit the results to be above a particular citation threshold, the query gets modified thusly:
```
(ack:NASA or aff: NASA and citation_count:[283 TO 9999999])
```
which due to the precedence of the boolean operators, is grouped as:
```
ack:NASA or (aff: NASA and citation_count:[283 TO 9999999])
```
rather than
```
(ack:NASA or aff: NASA) and citation_count:[283 TO 9999999]
```
And BTW I wonder if we shouldn't do the faceting via fq rather than q

**Comment by romanchyla** [comment]
will be closed by #444
