### ISSUE TITLE
Uncaught exceptions 

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#405]
The following query, issued from a results page (as opposed to the main search page) fails to return an error in response to a 400 error: https://api.adsabs.harvard.edu/v1/search/query?fl=title%2Cabstract%2Cbibcode%2Cauthor%2Ckeyword%2Cid%2Clinks_data%2Cproperty%2C%5Bcitations%5D%2Cpub%2Caff%2Cemail%2Cvolume%2Cpubdate%2Cdoi&hl=true&hl.fl=title%2Cabstract%2Cbody&q=(ack%3ANASA+or+aff%3ANASA)+AND+citation_count%3A%5B283+TO+*%5D&rows=25&sort=date+desc&start=0

**Comment by romanchyla** [comment]
now the error message appears again (related: https://github.com/romanchyla/montysolr/issues/29)
