### ISSUE TITLE
Fix query highlighter

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#407]
The highlighter used in BEER seems to work better than what is deployed in BBB.  Try a side-by-side comparison between the two systems to see the difference.  

It's possible (my guess) that we are not passing the right search parameters to SOLR?  In BEER, we use this: 
```
hl.q={!aqp}accomazzi
```

**Comment by aaccomazzi** [comment]
More to this: 

1. we need to add 'ack' to the list of fields to be highlighted.

2. The query terms sent to the highligher are manipulated to remove operators: https://github.com/adsabs/adsabs/blob/083d70ba399e965eda8c7ab70489b0192bd77a43/adsabs/core/solr/query_builder.py#L114

3. the following parameters are sent to solr:
```
    ('hl.maxAnalyzedChars', '150000'), 
    ('hl.requireFieldMatch', 'true'),
    ('hl.usePhraseHighlighter', 'true'),
```

Test queries that show the difference in highlight behavior are:
```
"hot jupiters"
NNX*
```

**Comment by romanchyla** [comment]
the last three settings helped, what beer does is in my opinion very wrong and i haven't used it; the highlights are now identical for the given examples

but i'm little bit worried about the maxAnalyzedChars to be so high; but when i set it lower, the ack highlights are missed (do we really need ack to be highlighted for unfielded searches? it works when you do specific 'ack:NNX*' search)

**Comment by aaccomazzi** [comment]
I'll check this out when this is deployed, but I think that yes, highlighting the acknowledgments is important, so if the cost is to increase the maxAnalyzedChars for the 20 records displayed by BBB, we should just do it.
