### ISSUE TITLE
Add "Edit this page on GitHub" link to the Help Pages

### ISSUE THREAD

**Issue by kelle** [adsabs/bumblebee#419]
Encourage/enable very interested users to help out with the Help pages. Check out the astropy docs (http://docs.astropy.org/en/latest/index.html), scroll to the bottom and notice they have an "Edit this page on GitHub" link. I may not contribute much code to astropy, but I have submitted several pull requests to the documentation!

**Comment by vsudilov** [comment]
This issue was moved to adsabs/help#7
