### ISSUE TITLE
getting an API Key documentation

### ISSUE THREAD

**Issue by kelle** [adsabs/bumblebee#421]
The documentation for getting an API key is presently blank
http://adsabs.github.io/help/api/api-key/
Consider just pasting this in:
If you would like to develop widgets or applications to interface with ADS services, you can generate an API Key by [creating an account] (https://www.google.com/url?q=https%3A%2F%2Fui.adsabs.harvard.edu%2F%23user%2Faccount%2Fregister)  and navigating to the API Token section in Settings. We are looking forward to seeing what the community builds with these services and encourage folks to requests API Keys several days in advance of any hack days.

**Comment by vsudilov** [comment]
This issue was moved to adsabs/help#5
