### ISSUE TITLE
make external links in docs popouts

### ISSUE THREAD

**Issue by kelle** [adsabs/bumblebee#422]
for example, on the Metrics help pages
http://adsabs.github.io/help/actions/
the links to Kurtz papers on arxiv and ADS should open in new windows/tabs.
If you want, I can make some of these suggested changes to the docs myself and issue a pull request.

**Comment by vsudilov** [comment]
Hi @kelle, thanks for the offer. PRs are always appreciated. The proper repo that contains this info is https://github.com/adsabs/help, and https://github.com/adsabs/help/tree/gh-pages/actions is where you want to look.

Just a note, I'm not sure we want to force the browser to open links in new tabs/windows, as it would be removing control of browser functionality from the user. Opinions @aholachek @aaccomazzi ?

**Comment by vsudilov** [comment]
This issue was moved to adsabs/help#6
