### ISSUE TITLE
speed up loading bbb

### ISSUE THREAD

**Issue by romanchyla** [adsabs/bumblebee#424]
either stop-gap measure: to prepare just the lean front page (and download other js libs in the background)

or, make the app lazy-load only libraries that are actually used in the current page AND do not actually create widgets (until they are requested)

so this issue is potentially big, with far reaching consequences (but still feasible)

first need to understand where the problem is:

- look at GA (load times)
- measure load times/execution (this is purely browser side)

**Comment by romanchyla** [comment]
this was too ambitious for IAU, changing milestone

**Comment by aholachek** [comment]
this was partially addressed by the concatenation, and presumably will be completely solved by the lazy loading, which is issue #458, so I'm closing this
