### ISSUE TITLE
remember selected items?

### ISSUE THREAD

**Issue by romanchyla** [adsabs/bumblebee#428]
the identifiers are put in the storage, but repeating the query doesn't select the previously selected papers

i guess because the query_mediator:105 clears the store (?)

**Comment by aholachek** [comment]
i think alberto said that every new search should clear the storage

**Comment by romanchyla** [comment]
i can understand the rationale, but it wont support one of the main use cases: search for my own papers (using different queries), select papers

if they selected something, it may be confusing that the system throws it away without their explicit action; seems more reasonable to me to have a 'clear all items from your basket' button

(and we may want to have a page that shows the 'selected items')

i guess we need more input...

**Comment by aholachek** [comment]
that's why we have libraries!

**Comment by romanchyla** [comment]
i'm reluctantly optimistic - libraries are becoming (yet again) the new cure for all world aches

**Comment by aaccomazzi** [comment]
I could go either way regarding the clearing of items, but the current solution seems reasonable: use it to select your sub-collection from the current query (through pagination), then ship it to persistent storage (library) if needed.  The only way to tell whether this is the best behavior is through usability feedback.
