### ISSUE TITLE
User signup problem prevents registration

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#440]
We received this bug report from a user.  To follow up @jonnybazookatone will check the logs to see what browser and OS she was using and if there is anything else odd in the logs.  Then @aholachek will attempt to reproduce the bug using her environment.  We should then deploy a fix to production asap.

Somewhat related to this, we should fix the headers so that email does not come from adslabs.org but rather ui.adsabs.harvard.edu I think.  We should also provide a contact email for user support (adshelp@cfa.harvard.edu).  Can you please do that @vsudilov?

```
From: no-reply@adslabs.org [mailto:no-reply@adslabs.org] 
Sent: Tuesday, June 30, 2015 9:39 PM
To: Pikas, Christina K.
Subject: [ADS] Please verify your email address
 
Hi, Someone (probably you) has registered this email address with the NASA-ADS (http://ui.adsabs.harvard.edu). To confirm this action, please visit undefined/#user/account/verify/register/ImNocmlzdGluYS5waWthc0BqaHVhcGwuZWR1Ig.CHTWHQ.Yzh3eT8ryiRW7W1s4BCCq5nWaLA with your browser. If this is a mistake, then just ignore this email. -The ADS team
```

**Comment by jonnybazookatone** [comment]
Within the logs;

"POST /v1/accounts/register HTTP/1.1" 200 22 "https://ui.adsabs.harvard.edu/#user/account/register" "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)"

The browser was [Windows IE](http://www.useragentstring.com/Internet%20Explorer11.0_id_19877.php).

**Comment by vsudilov** [comment]
@aaccomazzi that can't be done using AWS-SES (amazon email service) without putting the TXT dns record up. The TXT records verifies that we own the domain. We could sign up with another email service like mailchimp/mandrill, though.

**Comment by romanchyla** [comment]
the possible fix was merged, but the real solution will need to use bbb config;  see pr #437

**Comment by jonnybazookatone** [comment]
So I ran a [VMBox](http://dev.modern.ie/tools/vms/) with IE11 running on Windows 7, and tried to create an account on hourly. I was then e-mailed the standard confirmation page:

```
Hi, Someone (probably you) has registered this email address with the NASA-ADS 
(http://ui.adsabs.harvard.edu). To confirm this action, please visit 
http://hourly.adslabs.org/#user/account/verify/register/Impvbm55bmVsbGlvdHRAZ29vZ2xlbWFpbC5jb20i.CH2ayg.95lMkM9vTfbRzJY7_hljtkQFNyc 
with your browser. If this is a mistake, then just ignore this email. -The ADS team
 ```

So it looks like the fix worked, at least from this superficial testing.
