### ISSUE TITLE
Cached visualizations ignoring facets?

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#450]
This but is both in hourly and the deployed version.

1. Start from this query: https://ui.adsabs.harvard.edu/#search/q=(%22hot+jupiter%22+AND+year%3A2014-2015)&sort=date+desc
(936 results)

2. select the "refereed" filter: https://ui.adsabs.harvard.edu/#search/fq=%7B!type%3Daqp+v%3D%24fq_facets180%7D&fq_facets180=(property%3Arefereed)&q=(%22hot+jupiter%22+AND+year%3A2014-2015)&sort=date+desc
(582 results)

3. select Explore -> "paper network"; you see a network created on 300 out of 582 papers.  Looks good, now get out of the visualization and back to the 582 results

4. under "data" select "NExScI" filter: https://ui.adsabs.harvard.edu/#search/fq=%7B!type%3Daqp+v%3D%24fq_facets180%7D&fq=%7B!type%3Daqp+v%3D%24fq_data_facet%7D&fq_data_facet=(data_facet%3ANExScI)&fq_facets180=(property%3Arefereed)&q=(%22hot+jupiter%22+AND+year%3A2014-2015)&sort=date+desc
(68 results)

5. select Explore -> "paper network"; you will get the prior network (on 300 items) rather than one built on the smaller set as above

**Comment by romanchyla** [comment]
bbb is working well, but the microservice is using only the first parameter; i have submitted a patch, but Alex will have to review/integrate it and then also deploy into ELB

https://github.com/adsabs/vis-services/pull/7
