### ISSUE TITLE
OpenURL service endpoint undefined

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#451]
I'm looking at an abstract on hourly: http://hourly.adslabs.org/#abs/2013IAUC.9265....1G/abstract

And see a link which should take me to our openURL server:
http://hourly.adslabs.org/undefined?&url_ver=Z39.88-2004&rfr_id=info:sid/ADS&rft_val_fmt=info:ofi/fmt:kev:mtx:article&rft_id=info:bibcode/2013IAUC.9265....1G&rft.genre=article&sid=ADS&genre=article&isbn=undefined

Problems:
1. the endpoint is "undefined"
2. isbn should not be "undefined" and anyway should not be there at all (this is not a book)
3. I assume we will have the "Find it @ Harvard" icon instead of this generic link?  This is how people recognize their library links

**Comment by aholachek** [comment]
Is it important that they be recognized first as library links and second
as full-text links? i have that "university" icon with an explanatory
tooltip, otherwise I just assumed that people were generally more
interested in the full text and didn't care as much where it was coming
from.

If it is really important, I'll make it a louder button.

On Thu, Jul 9, 2015 at 12:54 PM, Alberto Accomazzi <notifications@github.com

**Comment by jonnybazookatone** [comment]
Also, not all of the gif links are working.

**Comment by aaccomazzi** [comment]
I think the way we have it in Classic is how we want it here as well:

1. the openURL link should display the institution's button when available
(so for us, it's http://sfx.hul.harvard.edu/hvd/sfx.gif)
2. the link should be in addition to (not as a replacement for) existing
full-text links



On Thu, Jul 9, 2015 at 1:01 PM, Jonny Elliott <notifications@github.com>
wrote:

> Also, not all of the gif links are working.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adsabs/bumblebee/issues/451#issuecomment-120070467>.
>



-- 
Dr. Alberto Accomazzi
Program Manager
NASA Astrophysics Data System - http://ads.harvard.edu
Harvard-Smithsonian Center for Astrophysics - http://www.cfa.harvard.edu
60 Garden St, MS 83, Cambridge, MA 02138, USA

**Comment by romanchyla** [comment]
I can't agree with the argumentation that 'the way how Classic does it' is the right way - if the gifs don't fit with the display (and branding, of which, you seem to be particularly fond of, Alberto :)) then it breaks the user experince in bbb

It is a function ("bring me to the fulltext") - and the function of the 'gif' is to communicate: "I'm bringing you to the fulltext"

**Comment by jonnybazookatone** [comment]
PR #452 should address your points 1. and 2. As for point 3., I think this should be left in the more general discussion in adsabs/issues/issues/34.
