### ISSUE TITLE
Error messages not visible

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#462]
If you have run a query in hourly, e.g. http://hourly.adslabs.org/#search/q=author%3A%22accomazzi%22&sort=date+desc
and then add a syntactically incorrect query string (e.g. "foo:bar") the user ends up seeing a spinning wheel.  The API does respond with a 400 and with a SOLR syntax error message but this never makes it to the UI.

**Comment by romanchyla** [comment]
i hit the similar error yesterday (from visualizations) - but i saw normal alerts; it is worrying me cause this used to work correctly and it is a tricky business; i'm not confident we can fix it before the freeze, but next week yes

**Comment by romanchyla** [comment]
fixed by 67cf6142868019cc8412227e541ee6f6c79ad0c6
