### ISSUE TITLE
Documentation: add some text to "Account Settings" -> "API Token" 

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#488]
At a minimum we should say "this is your current account token, and here is some info on how to use it with our API (link).
Also a word about generating a new key (and why somebody would want to do that)

**Comment by aholachek** [comment]
Roman says: 

t would be helpful to show the example of a curl command right under the API token page http://hourly.adslabs.org/#user/settings/token

curl -H 'Authorization: Bearer <actual-token-here>' 'http://api.adsabs.harvard.edu/v1/search/query?q=star'```
