### ISSUE TITLE
metrics is affected by the solr max rows

### ISSUE THREAD

**Issue by romanchyla** [adsabs/bumblebee#495]
We want to switch to sane conservative limits for /query - the rows parameter.

The metrics widget, however, right now is collecting the bibcodes in one swoop (e.g. rows=300, up to maximum 2000) and then sends them to metrics, possible solutions:

1. display a message "if  you want to get more, you need to login" (but this would require changes in the permission system, so it's more for the future)
2. collect the bibcodes using paging
3. send metrics the query and let it collect the bibcodes

The (2) is more work, but possibly cleaner; (3) is dirt cheap but I'd have to submit patch (metrics service right now uses only 'q' parameter)

**Comment by romanchyla** [comment]
the only advantage to (2) would be that we can limit the amount of bibcodes sent from the client, but i realized I could do the same with (3) if I make metrics accept rows limits and the full query

**Comment by vsudilov** [comment]
Just keep in mind that metrics is allowed to access rows=very many when it queries solr; we don't want to create a backdoor where a user can take advantage of that
