### ISSUE TITLE
Links to "view this list in a search results page" fail for A&A bibcodes

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#501]
The ampersand must be messing BB up.  For example:

this page renders properly: https://ui.adsabs.harvard.edu/#abs/2000A&AS..143....9W/citations

but when clicking the "view this list..." link, the url changes but the page contents don't: https://ui.adsabs.harvard.edu/#search/q=citations(bibcode:2000A&AS..143....9W)

**Comment by aaccomazzi** [comment]
I see the discussion in #513, is there a resolution on how to proceed?  This bug is pretty nasty as it affects all bibcodes with "&" in them so we need to close it.

**Comment by aholachek** [comment]
fixed by #557
