### ISSUE TITLE
http://localhost:8000/test/mocha/coverage.html failing for private libraries

### ISSUE THREAD

**Issue by romanchyla** [adsabs/bumblebee#528]
it passes tests, but not coverage - the check for the string condition is probably wrong

**Comment by romanchyla** [comment]
this was still failing today

**Comment by aholachek** [comment]
I thought my pull request increased coverage to the point that it wasn't a
problem anymore

**Comment by romanchyla** [comment]
for me it passes on 'grunt coverage' but fails when run in browser

two tests are checking a string (which fails)

**Comment by aholachek** [comment]
oh ok got it
