### ISSUE TITLE
autocomplete: too aggressive

### ISSUE THREAD

**Issue by romanchyla** [adsabs/bumblebee#542]
the search bar autocomplete is catching keys too fast - it even breaks selenium tests (and the computer is typing faster than me!)

it is typing:

t, i, t, l, e, :, f, o, o

but autocomplete catches ':' and offers () - but i continue typing and it ends up as
title:()

**Comment by aholachek** [comment]
roman, can we close this or is it still a problem?

**Comment by romanchyla** [comment]
let'sclose it , we can reopen if needed, thanks
