### ISSUE TITLE
Missing full-text links when openURL link is available

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#570]
We should not suppress links to PDF or HTML full-text content when we create an openURL link, since this hinders the user's capability of actually locating fulltext.  Log into your ADS account, setup a library link server and use the following example as an illustration:
https://ui.adsabs.harvard.edu/#abs/2015PhDT........21H/abstract

Compared with:
http://adsabs.harvard.edu/abs/2015PhDT........21H

Incidentally, I'm not sure that this openURL is properly created; at least ADS classic does not attempt to create them for PhD Thesis (without having an identifier such as a DOI that is).

**Comment by aholachek** [comment]
So there are two issues, one is that we are missing a check to see if the article is a thesis or something else that cannot have an open url.
The other question is even if the openurl is successfully created, do we need to create a regular ejournal link with the ads classic resolver as well? I thought this was redundant but maybe I am slightly confused

//current code from bumblebee
 if (!l.access && !scan_available && link_server){
            var openURL = new OpenURLGenerator(data, link_server);
            openURL.createOpenURL();
            electr_link = openURL.openURL;
            openUrl = true;
          } else {
            electr_link = this.adsUrlRedirect('electr', bib);
            openUrl = false;
          }


The link_data property for the article Alberto linked to was this:
["{"title":"", "type":"electr", "instances":"", "access":""}"]

**Comment by jonnybazookatone** [comment]
So your specification is the following Alberto;

  1. If there is a Thesis generate an openURL, only if it has a doi.
  2. Even if we make an openURL (as it is not open access and there is no ADS scan), you still want the PDF and fulltext links to be displayed.

**Comment by aaccomazzi** [comment]
Yes, Jonny got it right.  The openURL link should appear in addition to the existing electronic links (electr or pdf).

**Comment by aholachek** [comment]
Ok, now I understand, I can take care of 2) easily but maybe Jonny can fix 1)

**Comment by jonnybazookatone** [comment]
Yes, I can do 1), I'll add it to my todo list. From this mornings conversation, I assume I should work off of master and not IAU?

**Comment by jonnybazookatone** [comment]
Closed on my end. Let me know if something else is needed.
