### ISSUE TITLE
Garbled unicode in BB pages?

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#591]
I'm seeing incorrect unicode rendering in hourly for e.g. the author list in bibcode:2015ASPC..492..105P, although the page tells me the content is utf-8 encoded.

![image](https://cloud.githubusercontent.com/assets/910261/9773137/981543ae-570e-11e5-8d1a-4b12708f2615.png)

**Comment by aholachek** [comment]
@aaccomazzi  do you still get this error? I can't reproduce it

**Comment by aaccomazzi** [comment]
Looks fine now, go figure...
