### ISSUE TITLE
citations(first author) throws error

### ISSUE THREAD

**Issue by aholachek** [adsabs/bumblebee#593]
I think this is already a known bug but I can't find mention of it anywhere, Donna reported it again today:

https://ui.adsabs.harvard.edu/#search/q=citations(author%3A%22kurtz%2C+m%22)&sort=date+desc

causes a 500 error

**Comment by adsabs-beer-user** [comment]
Actually Alex I didn't use the first author query but just a
citations("author") query. . .  but the first author query also produces an
error.



On Mon, Sep 14, 2015 at 11:33 AM, Alex <notifications@github.com> wrote:

> I think this is already a known bug but I can't find mention of it
> anywhere, Donna mentioned it again to me today:
>
>
> https://ui.adsabs.harvard.edu/#search/q=citations(author%3A%22kurtz%2C+m%22)&sort=date+desc
>
> causes a 500 error
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adsabs/bumblebee/issues/593>.
>



-- 
Donna Thompson
Astrophysics Data System
Smithsonian Astrophysical Observatory
60 Garden Street, MS 83
Cambridge, MA 02138
(617)496-7660
dthompson@cfa.harvard.edu

**Comment by aholachek** [comment]
Ok, so maybe this is two separate issues, since the url you sent me was for a first author query, here it is:

https://api.adsabs.harvard.edu/v1/search/query?fl=title%2Cabstract%2Cbibcode%2Cauthor%2Ckeyword%2Cid%2Clinks_data%2Cproperty%2C%5Bcitations%5D%2Cpub%2Caff%2Cemail%2Cvolume%2Cpubdate%2Cdoi&hl=true&hl.fl=title%2Cabstract%2Cbody%2Cack&hl.maxAnalyzedChars=150000&hl.q=citations(author%3A%22%5Ekurtz%2C+m%22)&hl.requireFieldMatch=true&hl.usePhraseHighlighter=true&q=citations(author%3A%22%5Ekurtz%2C+m%22)&rows=20&sort=date+desc&start=0

and citations(author:"^kurtz,m") reliably throws a 500 in bbb, but citations(author:"kurtz,m") is working fine now at least

**Comment by aaccomazzi** [comment]
Same as: https://github.com/romanchyla/montysolr/issues/11
