### ISSUE TITLE
Bumblebee gets lost in navigation after paginating and follow-up query

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#607]
Start from a fulltext query of "foobar"

https://ui.adsabs.harvard.edu/#search/q=full%3A(foobar)&sort=date+desc

Then click on the link to take you to the third page at the bottom
Now search for "TMT whitepaper" in the fulltext:

https://ui.adsabs.harvard.edu/#search/q=full%3A(TMT+whitepaper)&sort=date+desc

the status bar says "9 papers returned" but none are visible

**Comment by aholachek** [comment]
I think this was fixed in IAU... so it shouldn't be in hourly once we
update it.

**Comment by aholachek** [comment]
this was just fixed -- the problem was the list_of_things widget was not clearing out its pagination model all the way when it was resetting it to the default state
