### ISSUE TITLE
Pagination and A&A bibcodes confuse abstract view

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#656]
Follow the steps below to reproduce a bug in the abstract display:
1. search for papers by Wambsganns in A&A: author:"wambsganss" bibstem:"A&A"
2. click on the first entry: 2015A&A...580A.125R
3. go back to list of results
4. go to next page by clicking on "2"
5. click on any entry on this page (e.g. 2008A&A...480..327A).  You will get the abstract view for the previously viewed paper (2015A&A...580A.125R)

Must still be the bug in encoding bibcodes with "&" in them.

**Comment by aholachek** [comment]
this has been fixed, it actually unfortunately wasn't the ampersand that was the issue, it was a problem with the abstract widget getting confused about which article abstracts it already had cached
