### ISSUE TITLE
ORCID settings does not detect lack of authentication

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#736]
If I'm logged into my ADS account but not yet authenticated into ORCID and I follow the link to ORCID settings, the UI should indicate that I'm not authenticated in ORCID, I think.

![image](https://cloud.githubusercontent.com/assets/910261/12057022/f0a245a4-af0a-11e5-9782-7b3f230e580a.png)

**Comment by aholachek** [comment]
Hi @aaccomazzi, are you sure you were not authenticated with orcid, rather than just having orcid mode switched off? I ask because i am getting the same error, a 404 for the preferences endpoint, in production, even when i am authenticated with orcid. The widget is set to only show you this form if you are authenticated with orcid, otherwise it should show you a button.

@romanchyla I'm getting a 404 on production for the preferences endpoint with my orcid id, here is the curl. I can't GET or POST. I know you said before that this was a result of a bad development config but that can't be related on production, right (?)   When I go to /resources, the /orcid/preferences/[orcid id] is listed, so it's definitely there.

      curl 'https://api.adsabs.harvard.edu/v1/orcid/preferences/0000-0003-3272-8867?_=1451745748086' -H 'Authorization: Bearer:gAXahb46vayEAL32jnxIkHUlKQwvXKd9mHCINwS6' -H 'Origin: https://ui.adsabs.harvard.edu' -H 'X-BB-Api-Client-Version: 20140329' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Referer: https://ui.adsabs.harvard.edu/' -H 'Orcid-Authorization: Bearer d70e85fa-a837-4264-8843-c78b2f4c82bb' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Cookie: NASA_ADSABS2_ID=4bbfbb70-2f2e-47c2-8ff7-ee3cb687da25; NASA_ADS_ID=51adef0569; NASA_ADS_TMP=; _gat=1; _ga=GA1.2.1691986789.1448404862; session=.eJw9j9FOgzAUQH_F3Oc9WNAXkj0sAZHFFotMcvtCgHXQFpgW2BzL_t2FRD_gnJNzhfxg5dCAN9pJriBXe_Cu8FCCB-hsFepW0WxHMN0R6nCCml6orgkLAyJCYWi6NbFv1nC7s1_SdkUv-_HPVg32kI9HI_t_aexvHNbxR-aIjmX4hBkS5tM59vmZ6cTgvLlg2nZs5g7Vwoi0_qHn9RI4FtPY5FWrlgScmiBu3rF_DSqjZJ1EbuS-lEVS7k_RR4j87Xue1GfLYQXTIO2yBs8u3H4BTP5QfQ.CWlzVA.KJnIJpj7G1tp3pvEEsuhw6jrAVQ' -H 'Connection: keep-alive' --compressed

**Comment by aaccomazzi** [comment]
Hi Alex, I think you are right, since when I'm logged off of orcid I get a different message.

**Comment by romanchyla** [comment]
@alex - pls compare (copy/paste) the normal orcid claim request with the
orcid prefernces request. Are the 'Orcid-Authorization' tokens the same?

**Comment by aholachek** [comment]
Hi @romanchyla, I'm actually unable to claim papers in Orcid on production right now
I get:
> API call failed: "//api.adsabs.harvard.edu/v1/orcid/0000-0003-3272-8867/orcid-profile?" 0 timeout
We have lost access to ORCID Api (maybe the user revoked the token?)

This is called in the "needsUpdate" method of the orcidapi. 

I tried to think if I've changed anything with the orcid api, the only change I've made to orcidapi is [this commit](https://github.com/adsabs/bumblebee/pull/722/files)

**Comment by romanchyla** [comment]
hi alex, i was able to claim without problems, i'm afraid you will have to
provide more details - that commit is not changing anything significant

are you still running this on localhost?
is some cached token interfering? (your local env)
did you check the Orcid-Authorization tokens and compare them - as per my
request above?

**Comment by aholachek** [comment]
hi @romanchyla , this is on production bbb that I'm having the problems. I am

-unable to claim orcid papers
-unable to load orcid preferences

However, I was able to load the orcid profile. the orcid-authorization token for that request is the same as for the failed requests I mentioned above.

**Comment by aholachek** [comment]
the timeout issue was fixed
