### ISSUE TITLE
bumblebee initial load time

### ISSUE THREAD

**Issue by aholachek** [adsabs/bumblebee#743]
two separate users at ads said unprompted to me "is there any way to make initial load time faster--i hate waiting the 1 or 2 seconds, even though the rest of the time it is fast"

**Comment by aholachek** [comment]
Related: 
-on slow connections bbb fails to load
-Carolyn's continuing experience of having to refresh the page to get it to load even on a fast connection

**Comment by thostetler** [comment]
duplicate #1396
