### ISSUE TITLE
overlapping 'debug' and 'hourly' directives in discovery.vars.js

### ISSUE THREAD

**Issue by romanchyla** [adsabs/bumblebee#745]
i didn't dig deeply - but the fact that the application checks whether it runs in production mode is suspicious; why is that?

additionally, the 'hourly' switch is also not documented - i've discovered it only because i'm porting the deployment files

**Comment by aholachek** [comment]
i'm pretty sure that's just to know whether to show the hourly banner at the top. Where should this be documented?

**Comment by romanchyla** [comment]
i'd document it in the discovery.config.vars - like the other variables

**Comment by aholachek** [comment]
i added the variable with short description to discovery.vars.js.default
