### ISSUE TITLE
Failure in encoding of facets

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#746]
Something seems to go wrong with either the display or encoding of author facets.  Take this example:

https://ui.adsabs.harvard.edu/#search/q=+author%3A%22^H%C3%B6rst%2C+S%22&sort=date+desc

And open the facet for "Hoerst, S":

![image](https://cloud.githubusercontent.com/assets/910261/12266209/e8f52948-b90f-11e5-8db4-f67dcf8ecb1a.png)

Apart from the wrong utf-8 characters, selection of these facets fails.

**Comment by ehenneken** [comment]
This bug seems to be solved
