### ISSUE TITLE
Make pages Zotero-friendly

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#752]
As explained here: https://forums.zotero.org/discussion/52851/translator-for-new-ads-site/

Ideally we use the embedded metadata approach which will make our pages more reference manager friendly in general.

**Comment by aaccomazzi** [comment]
See also #560

**Comment by aholachek** [comment]
I'm closing this since I think @aaccomazzi mentioned that the zotero people were going to change something on their end instead?
