### ISSUE TITLE
Orcid login leads to visualisations in middle

### ISSUE THREAD

**Issue by jonnybazookatone** [adsabs/bumblebee#761]
Not sure if this behaviour happens in hourly, but search isn't working atm, but stumbled across this recipe:

1. author:"Elliott, J."
2. Explore -> Author Network
3. Orcid Signin -> Take me to Orcid -> Signin
4. Redirect gives:

![orcid_vis_login](https://cloud.githubusercontent.com/assets/633540/12375199/4e104024-bc85-11e5-8309-4f978b344da9.png)

**Comment by aholachek** [comment]
hi @jonnybazookatone I tried to cache wherever the user was before the orcid sign in and redirect them there afterwards -- do you think it would be better to always redirect to the user's orcid page? If not, I see that the redirect back to ads didn't work perfectly anyway so I would have to look into why the search results page behind the visualization is empty. What do you think?

**Comment by jonnybazookatone** [comment]
I replied in person, but here is my in machine reply: as a user I am happy to be directed either to where I came from when doing the ORCiD access, or back to my ORCiD page. At this stage I had decided to give up what I was doing, and try via ORCiD, and so I didn't have any natural extension of my work flow.
