### ISSUE TITLE
hash issue in older safari browsers

### ISSUE THREAD

**Issue by aholachek** [adsabs/bumblebee#774]
Problem description:
When clicking a link (published on a website) to a personal ADS library ('Bumblebee' interface), for instance:
https://ui.adsabs.harvard.edu/#/public-libraries/s-zKxkshT2Wv14hLkCQImQ
the Safari browser opens a new tab and briefly shows the URL above, but then immediately reverts to just showing:
https://ui.adsabs.harvard.edu
(i.e. the ADS home page)

**Comment by aholachek** [comment]
could possibly be this (we do set the url 2x) this bug report is pretty old though.
http://www.howtocreate.co.uk/safari/locationHashBug.html

**Comment by aaccomazzi** [comment]
For the record, the URL works on my desktop running Yosemite (10.10.5) and Safari Version 9.0.3 (10601.4.4)
