### ISSUE TITLE
metrics plots for all papers, or individual papers

### ISSUE THREAD

**Issue by jonnybazookatone** [adsabs/bumblebee#776]
Both in devui/ui.

If you find any person who has published this year and look at their metrics plots, you will find that 2016 is being plotted at 0.

From a quick glance, I noticed that the metrics end point is returning arrays that have the order:
```
... {'all_reads':
2016: 1
1999: 1
2000: 1
2001: 1
2002: 1
2003: 1
2004: 1
2005: 1
....
2014: 1
2015: 1
}
```
![pic](https://cloud.githubusercontent.com/assets/633540/12661772/a0a954de-c5e9-11e5-94ee-0bda90a2b8d0.png)

So it may be the plots are being done based on the order of the input, rather than based on the date.

**Comment by aholachek** [comment]
closing since upgrading to most recent firefox version fixed the issue
