### ISSUE TITLE
link to bumblebee needed from ADShelp pages

### ISSUE THREAD

**Issue by donnat** [adsabs/bumblebee#796]
help pages should link back to search pages

**Comment by jonnybazookatone** [comment]
Do you have any specific examples that come to mind when you filed this issue? I will also move this issue to the help repository, as there shouldn't need to be any changes made to bumblebee.

**Comment by adsabs-beer-user** [comment]
If I am just looking at the help pages I can't easily get back to
Bumblebee.

I see that a new tab opens for help if I'm already doing a search but if I
start by looking at the help pages there isn't a link to get to search.

Donna

On Tue, Feb 16, 2016 at 12:31 PM, Jonny Elliott <notifications@github.com>
wrote:

> Do you have any specific examples that come to mind when you filed this
> issue? I will also move this issue to the help repository, as there
> shouldn't need to be any changes made to bumblebee.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adsabs/bumblebee/issues/796#issuecomment-184788272>.
>



-- 
Donna Thompson
Astrophysics Data System
Smithsonian Astrophysical Observatory
60 Garden Street, MS 83
Cambridge, MA 02138
(617)496-7660
dthompson@cfa.harvard.edu

**Comment by jonnybazookatone** [comment]
OK, I understand, makes a lot of sense. I'll move this issue to the help repo.

**Comment by jonnybazookatone** [comment]
See adsabs/adsabs.github.io/issues/43.
