### ISSUE TITLE
user suggested ui improvement

### ISSUE THREAD

**Issue by aholachek** [adsabs/bumblebee#800]
2. When the list of results appear, there should be something to separate them, such as a line, or even a light colored background every two abstracts. Currently, when looking for the details of a result in the list, I sometimes look at the details of the result below it.

**Comment by aholachek** [comment]
I think this is a good idea in theory but in practice it adds a lot of visual weight, maybe if another user complains about this I can reopen

**Comment by romanchyla** [comment]
I agree. Maybe you could try 10px wide line, just in the middle as a
separator (it could help guide the eye,  so that the gaze cannot jump
up/down to the next article)
