### ISSUE TITLE
detect user agent and send as hidden field in feedback form

### ISSUE THREAD

**Issue by aholachek** [adsabs/bumblebee#810]

**Comment by aholachek** [comment]
Cursory googling leads me to believe this will be [way harder than anticipated](https://developer.mozilla.org/en-US/docs/Browser_detection_using_the_user_agent), for instance my chrome browser is currently claiming to be Netscape (values are in the navigator object)

**Comment by aaccomazzi** [comment]
If you have access from javascript to the User-Agent HTTP header, then you should just send that along with the feedback request.

Even though browsers use some fakery to claim compatibility, there are websites such as http://useragentstring.com/ which allow you to analyze that string and give you back some useful information.

**Comment by aholachek** [comment]
@jonnybazookatone when you get a chance ,could you please look at  pull request #815 and see if you could change the feedback back end to accept this new field?
