### ISSUE TITLE
Comments in each record

### ISSUE THREAD

**Issue by jradavenport** [adsabs/bumblebee#846]
- comments are not displayed in the UI
- comments are not searchable

Example:

http://adsabs.harvard.edu/abs/2015arXiv151005695D

versus

https://ui.adsabs.harvard.edu/#abs/2015arXiv151005695D/

**Comment by aholachek** [comment]
@romanchyla is this field indexed in solr? It's not mentioned in the API docs

**Comment by romanchyla** [comment]
@aaccomazzi can I index/store the two fields into `comments`? Or do they actually contain pieces of information that need to be kept separate?

**Comment by aaccomazzi** [comment]
No, let's keep them separate.  "pubnote" has a very specific meaning and should be searchable on its own.

BTW I believe that "comment" is already a field based on what I see here: https://github.com/adsabs/ADSimportpipeline/blob/bb2390b3f22741f8d612ce5f8c8024fbc529e590/lib/SolrUpdater.py#L84
Can you please confirm?

**Comment by romanchyla** [comment]
yes, `comment` is being populated
