### ISSUE TITLE
Add expiration headers to bumblebee

### ISSUE THREAD

**Issue by aholachek** [adsabs/bumblebee#852]
hi @romanchyla according to [google's pagespeed service](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdevui.adsabs.harvard.edu%2F&tab=mobile) bumblebee isn't caching properly since the expiration headers are not being provided.

It also says svg images are not being served with gzip compression.

**Comment by romanchyla** [comment]
ok, i've made changes to nginx - pretty much everything gets cached/gzipped

besides the index.html (and the styles.css and require.js; an I can't figure out why the style is not cached by chrome; maybe because it is referenced by index.html?)
