### ISSUE TITLE
"^" for first author causing error in second degree queries (citations, references, reviews) 

### ISSUE THREAD

**Issue by donnat** [adsabs/bumblebee#861]
![screen shot 2016-03-17 at 1 30 14 pm](https://cloud.githubusercontent.com/assets/5231037/13855177/73bf8182-ec45-11e5-87cf-7b8ff193564e.png)

**Comment by aaccomazzi** [comment]
Thanks for reporting this.  It is a known bug in montysolr: https://github.com/romanchyla/montysolr/issues/11

As a workaround, use first_author:XXX or the pos() syntax as discussed there until fixed.  

Bump @romanchyla

**Comment by aholachek** [comment]
since this isn't a bumblebee-related bug I'm going to close it
