### ISSUE TITLE
Provide h-index filtered by self-cites

### ISSUE THREAD

**Issue by Gabriel-p** [adsabs/bumblebee#893]
Currently the h-index provided by bumblebee's interface is not filtered by self-cites.

It'd be great if an option could be added.

**Comment by ehenneken** [comment]
Thank you for the suggestion. Currently we don't have any plans for extending the metrics. We highly recommend the Tori index, which is not only corrected for self-citations, but also takes into account that different disciplines have different citation rates. You can, if you wish, calculate versions of other citation-based indicators, corrected for self-citations, by using our API (https://github.com/adsabs/adsabs-dev-api).

**Comment by Gabriel-p** [comment]
Thank you very much @ehenneken for letting me know about the tori index, I wasn't aware of it.

I just checked the Metrics section of bumblebee and I saw that one and many others I also didn't know about.
