### ISSUE TITLE
riq index in 'Metrics' wrongly obtained?

### ISSUE THREAD

**Issue by Gabriel-p** [adsabs/bumblebee#894]
The riq index is:

> the square root of the tori index, divided by the time between the first and last publication

See for example [here](https://ui.adsabs.harvard.edu/#search/q=author%3A%22einstein%22&sort=date%20desc/metrics) where the value given is clearly wrong. I've checked several authors, the riq value is always wrong.

Also, the description that appears when the mouse hovers over the `?` symbol says "roq" instead of "riq", both in the title and the body.

**Comment by ehenneken** [comment]
Actually (and we should update the help to reflect this and correct 'roq' into 'riq'), the value display is 1000 times that ratio, turned into an integer. Thank you for pointing this out.
