### ISSUE TITLE
Interrupted loading of records 25-50 in results page

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#915]
This happened a few times now and then: I have selected 50 as the number of results I want in my page and now and then records 26-50 are not loaded.  This just happened and when I checked the console I see this:
```
Failed to load resource: the server responded with a status of 400 (BAD REQUEST)
https://api.adsabs.harvard.edu/v1/search/query?fl=title%2Cabstract%2Cbibcode%2Cauthor%2Ckeyword%2Cid%2Clinks_data%2Cproperty%2Ccitation_count%2C%5Bcitations%5D%2Cpub%2Caff%2Cemail%2Cvolume%2Cpubdate%2Cdoi&hl=true&hl.fl=title%2Cabstract%2Cbody%2Cack&hl.maxAnalyzedChars=150000&hl.q=title%3A%22%22&hl.requireFieldMatch=true&hl.usePhraseHighlighter=true&q=title%3A%22%22&rows=25&sort=date%20desc&start=0
```
(upon inspection I can't figure out why the request displayed is for rows=0)

**Comment by aholachek** [comment]
this does not seem to be a problem in hourly, I believe it was fixed in pull request #908
