### ISSUE TITLE
Link in 'Paper Network' page is dead

### ISSUE THREAD

**Issue by Gabriel-p** [adsabs/bumblebee#916]
See foe example: https://ui.adsabs.harvard.edu/#search/q=author%3A%22Mattas%2C%20R.%22&sort=date%20desc/paper-network

The link in *Learn more about how ADS networks are created and how they can be used.* is https://adsabs.github.io/help/actions/visualize/ which returns a 404.

**Comment by jonnybazookatone** [comment]
GitHub is strict with the slashes, the real URL is:

https://adsabs.github.io/help/actions/visualize

**Comment by jonnybazookatone** [comment]
Thanks for noticing the issue @Gabriel-p. Should be fixed when @aholachek has looked at my PR.

**Comment by aholachek** [comment]
the fix was merged but not yet deployed, thanks @Gabriel-p
