### ISSUE TITLE
Accessible fields from the QueryBuilder plugin

### ISSUE THREAD

**Issue by jonnybazookatone** [adsabs/bumblebee#921]
We've been trying to consolidate what fields are, and whether we want them to be shown to the user. Some of the fields accessible from the QueryBuilder probably don't need to be there.

These should be deprecated, and no longer encouraged to be used:
 * Citation - `citation`
 * Reference - `reference`

These have related privacy issues and shouldn't be encouraged:
 * Email - `email`
 * SIMBAD ID - `simbid`

These I don't know what they are used for, and are probably not useful for generic users:
 * position() - `pos()`
 * Version - `__version__`

These I think are confusing and not necessarily needed for users building a query:
 * Author Facet - `author_facet`
 * Electronic ID - `eid` (I guess if librarians want to use it, this is the only use case)
 * Indexstamp - `indexstamp` (I can't think of a good use case on the UI)
 * ID - `id` (I can't think of a good use case on the UI, unless you want to match client results with UI)

These are not populated in Solr yet, and are still a work in progress, and so I would remove them for now until we're happy to use them:
 * Comment - `comment`
 * Facility - `facility`
 * ISBN - `isbn`
 * ISSN - `issn`
 * Thesis - `thesis`

Finally, do we want to make accessible the individual ORCiD fields, if we envisage librarians using this query builder (see statement about `eid` above):
 * `orcid_*`

@aaccomazzi can you please mention the relevant people who you'd like to comment on the suggestions.

**Comment by jonnybazookatone** [comment]
Feel free to voice outrage at my suggestions. Some of the decisions above were driven by how we should behave towards the client.

**Comment by romanchyla** [comment]
Pos() is useful and should stay.

I agree about the rest. However, better solution is to keep those fields
inside qbuilder (and even add others!) And just hide them from the view.
Because those fields tell qbuilder how to parse stuff. So if one uses
timestamp in the query (and you can do that), qbuilder can still understand
it.

**Comment by aaccomazzi** [comment]
Agree with what Roman says.  In terms of ORCID, we should simply expose the "orcid" virtual field, which will search all three.  The orcid_* fields remain searchable but not present in the menu.

**Comment by aaccomazzi** [comment]
Forgot to mention, we should of course add the object field once SIMBAD integration is complete, but will that work out of the box?  Since there is a translation step between object and simbid I'm not sure what qbuilder ends up doing.  @ehenneken may need to keep this in mind

**Comment by csgrant00** [comment]
I'd like to see  comment incorporated into solr and made available
to users.   Some of the stuff in there is useful.


--Carolyn
*************************************************************************
       Carolyn Stern Grant              Astrophysics Data System (ADS)
       cgrant@cfa.harvard.edu           Center for Astrophysics
       617-495-7154 (voicemail)         60 Garden Street  MS 83
       617-495-7356 fax                 Cambridge, MA  02138
*************************************************************************

**Comment by aaccomazzi** [comment]
Agree, @csgrant00.  FYI, we have an open issue about this: https://github.com/adsabs/issues/issues/70

**Comment by csgrant00** [comment]
Missing from this list, AFAIK, are the non-SIMBAD objects.
Are these in solr yet?  I think they should be.

--Carolyn
*************************************************************************
        Carolyn Stern Grant              Astrophysics Data System (ADS)
        stern@cfa.harvard.edu            Center for Astrophysics
        617-495-7154 (voicemail)         60 Garden Street  MS 83
        617-495-7356 fax                 Cambridge, MA  02138
*************************************************************************

**Comment by jonnybazookatone** [comment]
Can someone with the proper context open a ticket for this (@csgrant00, @aaccomazzi ?)

**Comment by aaccomazzi** [comment]
Indexing of objects will require some thinking and implementing, and is addressed by https://github.com/adsabs/issues/issues/74

For the time being we should just have "object" run the current object search.

**Comment by jonnybazookatone** [comment]
So in summary (please correct if misunderstood), we should hide the following options in the QueryBuilder:

 * Citation - `citation`
 * Reference - `reference`
 * Email - `email`
 * SIMBAD ID - `simbid`
 * Version - `__version__`
 * Author Facet - `author_facet`
 * Electronic ID - `eid` (I guess if librarians want to use it, this is the only use case)
 * Indexstamp - `indexstamp` (I can't think of a good use case on the UI)
 * ID - `id` (I can't think of a good use case on the UI, unless you want to match client results with UI)
 * Comment - `comment`
 * Facility - `facility`
 * ISBN - `isbn`
 * ISSN - `issn`
 * Thesis - `thesis`

**Comment by aholachek** [comment]
I am closing this issue given the decisions we made about refraining from updating the query builder at this time
