### ISSUE TITLE
SIMBAD facets display shows incorrect labels

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#934]
Search for LMC, select "Galaxy" under SIMBAD facets, then select "Star" under SIMBAD facets.  You will see that the first facet label displays "Object +simbad_object_facet_hier:0\/Galaxy" rather than "Object: Galaxy" as expected.

https://ui.adsabs.harvard.edu/#search/fq=%7B!type%3Daqp%20v%3D%24fq_simbad_object_facet_hier%7D&fq_simbad_object_facet_hier=((simbad_object_facet_hier%3A0%5C%2FGalaxy)%20AND%20simbad_object_facet_hier%3A0%5C%2FStar)&q=LMC&sort=date%20desc&sort=bibcode%20desc

**Comment by ehenneken** [comment]
I'm unable to reproduce this on my local branch

**Comment by aholachek** [comment]
I can reproduce this on dev ui consistently

**Comment by ehenneken** [comment]
I added a `case` in the "filter_visualizer" widget in the `beautifyOperand` method to clean up the bread crumb for the SIMBAD facet

**Comment by aholachek** [comment]
I think this has been resolved?

**Comment by ehenneken** [comment]
When I select a top level facet (like `Galaxy`) to filter, I see `+0/Galaxy`, rather than just `+Galaxy`. Is that an easy fix?

**Comment by aholachek** [comment]
fixed!
