### ISSUE TITLE
myADS

### ISSUE THREAD

**Issue by Gabriel-p** [adsabs/bumblebee#947]
Will the *Notification Service* from [myADS](http://myads.harvard.edu/) be ported here too? Any ETA?

**Comment by ehenneken** [comment]
Hi Gabriel

Eventually, yes. We don't have an ETA yet.

Best wishes
Edwin

**Comment by aaccomazzi** [comment]
Something must be wrong with your account.  Please write to ads@cfa.harvard.edu with your login details so we can look into it.

**Comment by Gabriel-p** [comment]
It's not the account, it's the browser. The described behavior occured with Chrome 63.0.3239.132 (64 bits), but not with Firefox 57.0.4 (64-bit). I cleared the cookies and Chrome now lets me access. Thanks @aaccomazzi.
