### ISSUE TITLE
Incorrect breadcrumb labeling

### ISSUE THREAD

**Issue by ehenneken** [adsabs/bumblebee#948]
Example: do query `star`. Open author facet and select entry `Wang, J.S.` with "limit to". The breadcrumb displays `+Wang, J/Wang, J. S.` rather than `+Wang, J. S.` (which should be the case, right?). Select a next author with "limit to", which adds a next breadcrumb. Doing this one more time, instead of getting a third breadcrumb, results in a single breadcrumb `custom filter`.

**Comment by aholachek** [comment]
I think  "custom filter" is on purpose to prevent too many breadcrumbs. As for the first issue, I can change it to only listing the second name... @romanchyla do you agree that this should be changed, or was the part in front of the slash on hierarchical facets included on purpose?
